### ISSUE TITLE
Input Rules

### ISSUE THREAD

**Issue by cmmartin2514** [CMPUT301F21T36/OldHabitsDieHard#91]
- require a habit title, if empty make an error
- require a habit event comment, if empty make an error

EXTRA:
- minimum username length (6 characters? 8?)
- minimum password length (8 characters?)
- require certain characters in password (a symbol, uppercase/lowercase letters, etc)

**Comment by Chanpreet-Singh-UofA** [comment]
Done, merged by Clair in her bug fix.
